---


- name: Enable oVirt 4.1 repo
  yum:
    name: http://resources.ovirt.org/pub/yum-repo/ovirt-release41.rpm
    state: present

<<<<<<< HEAD:roles/ovirt/tasks/install-ovirt-engine.yaml
- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

=======
>>>>>>> 07f2c41a6bdaecd4bda6ff57c318283bf8863597:roles/ovirt-engines/tasks/install-ovirt-engine.yaml
- name: Install oVirt 4.1
  yum:
    name: ovirt-engine
    state: present

- name: Install Pip
  yum:
    name: python-pip
    state: present

- set_fact:
    engine_fqdn: "{{ ansible_fqdn }}"
    engine_domain: "{{ ansible_domain }}"
  when: not engine_manual

- name: Changing the hostname to match the Engine FQDN
  hostname:
        name: "{{ engine_fqdn }}"

- name: Generate /etc/hosts file
  template:
        src: hosts.j2
        dest: /etc/hosts

- name: Adding answer.txt file
  template:
          src: answer.j2
          dest: /root/answer.txt

- name: Initialize the oVirt-engine
  command: engine-setup --config=/root/answer.txt
  args:
        creates: /var/lib/pgsql/data/*

  #- name: Initialize the oVirt-engine
  #  expect:
  #        command: engine-setup --config=/root/answer.txt
  #        responses:
  #                "backup" : "No"
  #                "stopped" : "OK"
  #        timeout: 600
  #        echo: yes
  #  register: prompt
  #
  #- debug:
  #        var: prompt.stdout_lines
