---

- hosts: servers
  gather_facts: False

  tasks:


          - name: Install python2
            raw:  test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

          - name: Install Openstack Repos
            apt:
                 name:  software-properties-common
                 state: present

          - name: Add Openstack Repo       
            apt_repository:
                repo:   deb http://ubuntu-cloud.archive.canonical.com/ubuntu xenial-updates/newton main
                state:  present

          - name: super-ugly hack to allow unauthenticated packages to install
            copy: content='APT::Get::AllowUnauthenticated "true";' dest=/etc/apt/apt.conf.d/99temp owner=root group=root mode=0644

          - name: Update and dist-upgrade
            apt:
                update_cache: yes
                upgrade: dist
                state: latest

          - name: Install Openstack Client
            apt:
                name:   python-openstackclient
                state:  present

                # - name: remove hack that allows unauthenticated packages to install
                #file: path=/etc/apt/apt.conf.d/99temp state=absent

          - easy_install:
                   name: pip
                   state: latest

          - name: install shade
            pip:
                name: shade
                state: present
